# Generated by Django 4.2.8 on 2023-12-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("initial_access", "0002_alter_initaccess_option_a_alter_initaccess_option_b"),
    ]

    operations = [
        migrations.RemoveField(model_name="privescalation", name="keywords",),
        migrations.RemoveField(model_name="privescalation", name="option_C",),
        migrations.RemoveField(model_name="privescalation", name="option_D",),
    ]
