# Generated by Django 4.2.8 on 2023-12-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initial_access", "0003_remove_privescalation_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privescalation",
            name="option_A",
            field=models.CharField(default="yes", max_length=200),
        ),
        migrations.AlterField(
            model_name="privescalation",
            name="option_B",
            field=models.CharField(default="no", max_length=200),
        ),
    ]
