# Generated by Django 4.2.8 on 2023-12-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initial_access", "0004_alter_privescalation_option_a_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="initaccess",
            name="keywords",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="privescalation",
            name="keywords",
            field=models.TextField(blank=True),
        ),
    ]
