# Generated by Django 4.2.8 on 2023-12-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initial_access", "0005_initaccess_keywords_privescalation_keywords"),
    ]

    operations = [
        migrations.RemoveField(model_name="commandcontrol", name="option_C",),
        migrations.RemoveField(model_name="commandcontrol", name="option_D",),
        migrations.RemoveField(model_name="credentialaccess", name="option_C",),
        migrations.RemoveField(model_name="credentialaccess", name="option_D",),
        migrations.AlterField(
            model_name="commandcontrol",
            name="option_A",
            field=models.CharField(default="yes", max_length=200),
        ),
        migrations.AlterField(
            model_name="commandcontrol",
            name="option_B",
            field=models.CharField(default="no", max_length=200),
        ),
        migrations.AlterField(
            model_name="credentialaccess",
            name="option_A",
            field=models.CharField(default="yes", max_length=200),
        ),
        migrations.AlterField(
            model_name="credentialaccess",
            name="option_B",
            field=models.CharField(default="no", max_length=200),
        ),
    ]
