# Generated by Django 4.2.8 on 2023-12-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initial_access", "0006_remove_commandcontrol_option_c_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="responses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.IntegerField()),
                ("initial_access_result", models.IntegerField()),
                ("privescalation_result", models.IntegerField()),
                ("credentialaccess_result", models.IntegerField()),
                ("commandcontrol_result", models.IntegerField()),
            ],
        ),
    ]
