# Generated by Django 4.2.8 on 2023-12-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initial_access", "0007_responses"),
    ]

    operations = [
        migrations.CreateModel(
            name="collections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.CharField(max_length=200)),
                ("question", models.TextField(blank=True)),
                ("option_A", models.CharField(default="yes", max_length=200)),
                ("option_B", models.CharField(default="no", max_length=200)),
                ("keywords", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="execution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.CharField(max_length=200)),
                ("question", models.TextField(blank=True)),
                ("option_A", models.CharField(default="yes", max_length=200)),
                ("option_B", models.CharField(default="no", max_length=200)),
                ("keywords", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="impact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.CharField(max_length=200)),
                ("question", models.TextField(blank=True)),
                ("option_A", models.CharField(default="yes", max_length=200)),
                ("option_B", models.CharField(default="no", max_length=200)),
                ("keywords", models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(name="responses",),
    ]
